#!/bin/sh
#
# nginx - this script starts and stops the nginx daemon
#
# chkconfig:   - 85 15
# description:  NGINX is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: nginx
# config:      /etc/nginx/nginx.conf
# config:      /etc/sysconfig/nginx
# pidfile:     /var/run/nginx.pid

nginx=nginx
prog=nginx

start() {

    echo -n $"Starting $prog "
    nginx
    echo ""
    return 0
}

stop() {
    echo -n $"Stopping $prog "
    pkill nginx
    echo ""
    return 0
}

restart() {
    echo -n $"Restarting $prog "
    #pkill nginx
    kill $(pgrep -f nginx | grep -v ^$$\$)
    sleep 2
    echo ".."
    nginx
    return 0
}

configtest() {
  nginx -t
}


case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    configtest)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|configtest}"
esac